version: 2

before:
  hooks:
    - go mod download
builds:
- env:
    - CGO_ENABLED=0
  ldflags:
    - -s -w -X github.com/Mario-F/hetzner-dyndns/cmd.Version=v{{.Version}}
  goos:
  - freebsd
  - linux
  - windows
  - darwin
  goarch:
  - 386
  - amd64
  - arm
  - arm64
  goarm:
  - 6
  - 7
archives:
  - name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- if eq .Os "darwin" }}Darwin
      {{- else if eq .Os "linux" }}Linux
      {{- else if eq .Os "windows" }}Windows
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "arm" }}armv{{ .Arm }}
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
